config/routes.rb
OfficeCalendar::Application.routes.draw do

  root :to => 'home#index'
  get 'admin' => 'home#admin', as: 'admin'
  post 'admin' => 'home#create_holiday', as: 'create_holiday'
  match 'holidays' => 'home#holidays'

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  attr_accessible :date, :name
  validates :date, :presence => true
  validates :name, :presence => true


  OFF_DAYS = ['sat','sun'] #Change this to set-up off days

  def self.holiday_between start_date,end_date
    where(:date => start_date..end_date).select('date,name')
  end

  def self.holiday_around
    where(:date => 1.month.ago.beginning_of_month.to_date..1.month.from_now.end_of_month.to_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @holiday_around = Holiday.holiday_around.group_by{|hol| hol.date.month }
  end

  def admin
    @admin = {name: 'Mr.Administrator', role: 'admin'}
    @holiday = Holiday.new
    @holidays = Holiday.all
  end

  def create_holiday
    @holiday = Holiday.new(params[:holiday]).merge!(date: params[:holiday][:date].to_date)
    @holiday.save!
    redirect_to admin_path
  end

  def holidays
    start_date = DateTime.strptime(params[:start],'%s')
     end_date =  DateTime.strptime(params[:end],'%s')
     holiday_dates = Holiday.holiday_between start_date, end_date
     holiday_dates_hash = [Holiday::OFF_DAYS, hash_from_holiday_object(holiday_dates)]
    render :json => holiday_dates_hash
  end

  private
  def hash_from_holiday_object(holidays)
    h =  Hash.new
    holidays.each do |holiday|
      h[holiday.date.to_date] = holiday.name
    end
    h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<% provide(:title, 'Office Calendar - Admin') %>
<div class="muted"><h3>Hi <%= @admin[:name] %>, welcome to OfficeCalendar admin page</h3></div>

<%= form_for(@holiday, :url => create_holiday_path ,:html => {class:'form-horizontal'}) do |f| %>
  <div class='control-group'>
    <%= f.label :date, class: 'control-label' %>
    <div class='controls'>
     <%= f.text_field :date, class: 'datepicker' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :name, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :name %>
    </div>

  </div>
  <div class='control-group'>
    <div class='controls'>
        <%= f.submit 'Create Holiday', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Holiday Name</th>
    </tr>
  </thead>
  <tbody>
<% @holidays.each_with_index do |holiday, i| %>
    <tr>
      <td><%= i + 1 %></td>
      <td><%= holiday.date.to_date %></td>
      <td><%= holiday.name %></td>
    </tr>
<% end %>
</tbody>
</table>
<script type='text/javascript'>
var OffDays = <%= ['sat','sun'].to_json.html_safe %>;
</script>

app/views/home/index.html.erb
<%= provide(:title, 'Office Calendar') %>
<div class='span9'>
<div class='top_header'><h3>Welcome to Office Calendar<h3></div>
<div id='calendar'></div>
</div>
<div class="span3">
            <div class="well sidebar-nav pull-right">
              <h3>Holidays</h3>
              <ul class="nav nav-list">
                <% @holiday_around.each do |month, holidays| %>
                  <li class="nav-header"><%= Date::MONTHNAMES[month] %></li>
                  <% holidays.each do |holiday| %>
                    <%= "#{holiday.date.to_date}   =>   #{holiday.name}" %>
                  <% end %>
                  <% end %>
              </ul>
            </div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OfficeCalendar" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">OfficeCalendar</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <!-- <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
             -->
           </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">

            <%= bootstrap_flash %>
            <%= yield %>

        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>